server:
  address: "http://localhost:8080"
  context_root: "/api/v1"

resources:
  row_data:
    url_one: "/data"
    url_batch: "/datas"
  trainings:
    uri: "/trainings"
    verbs:
      start: ""
      stop: "/stop"

bluetooth:
  scrap:
    interval: 1


batch:
  isActive: False
  bytime:
    isActive: False
    interval_seconds: 5
  bysize:
    isActive: False
    size: 10

mock:
  send:
    isActive: True